# Generated by Django 5.0.4 on 2024-04-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
